name: Hourly PR Data Update

on:
  schedule:
    # 1時間ごとに実行（UTC時間）
    - cron: "0 * * * *"
  workflow_dispatch: # 手動実行も可能にする

jobs:
  update-pr-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pr_analysis repository
        uses: actions/checkout@v3
        with:
          repository: team-mirai-volunteer/pr_analysis
          token: ${{ secrets.GH_TOKEN }}
          path: pr_analysis

      - name: Checkout pr-data repository
        uses: actions/checkout@v3
        with:
          repository: team-mirai-volunteer/pr-data
          token: ${{ secrets.GH_TOKEN }}
          path: pr-data

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          cd pr_analysis
          pip install -r requirements.txt

      - name: Run PR data collection
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd pr_analysis
          python src/collectors/pr_collector_main.py --config config/settings.yaml --output-dir ../pr-data/prs

      - name: Generate label reports
        run: |
          cd pr_analysis
          python src/generators/label_report_main.py --config config/settings.yaml --input-dir ../pr-data/prs --output-dir ../pr-data/reports/labels

      - name: Generate section reports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd pr_analysis
          python src/analyzers/section_analyzer_main.py --config config/settings.yaml --input-dir ../pr-data/prs --output-dir ../pr-data/reports/sections

      - name: Commit and push to pr-data repository
        run: |
          cd pr-data
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # PRデータの変更をコミット
          git add prs/ indexes/ reports/
          
          # 変更がある場合のみコミットする
          if git diff --staged --quiet; then
            echo "No changes to commit for pr-data repository"
          else
            timestamp=$(TZ=Asia/Tokyo date '+%Y-%m-%d %H:%M:%S JST')
            git commit -m "Update PR data and reports - ${timestamp}"
            git push
            echo "Changes pushed to pr-data repository"
          fi
